### ISSUE TITLE
Error in plugin after start

### ISSUE THREAD

**Issue by rlust** [steinis123/IndigoHAplugin#2]
I have added several devices from HA and now getting an error during run:

Any ideas to look at?
Running HA 0.102.3

Started plugin "Home Assistant 1.0.4"
   Home Assistant                  Starting device with address: cover.main
   Home Assistant                  Starting device with address: cover.garage_door_opener_2
   Home Assistant                  Starting device with address: binary_sensor.closet_motion
   Home Assistant                  Starting device with address: binary_sensor.garage_motion_rf
   Home Assistant                  Starting device with address: binary_sensor.multisensor_motion_2
   Home Assistant                  Starting device with address: binary_sensor.ring_front_door_motion
   Home Assistant                  Starting device with address: binary_sensor.hai_motion_shop
   Home Assistant                  Starting device with address: light.office
   Home Assistant                  Starting device with address: binary_sensor.office_motion
   Home Assistant                  Starting device with address: light.led_office
   Home Assistant                  Starting device with address: light.led2
   Home Assistant                  Starting device with address: sensor.duct_temp
   Home Assistant                  Starting device with address: sensor.hot_water_pipe
   Home Assistant                  Starting device with address: person.kim
   Home Assistant                  Starting device with address: switch.motion_esp32_switch
   Home Assistant                  Starting device with address: binary_sensor.garage_motion_rf
   Home Assistant                  Starting device with address: person.randy
   Home Assistant Error            Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 266, in runConcurrentThread
KeyError: u'last_updated'

   Home Assistant Error            plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)
   Trigger                         new trigger test mqtt pub office Mast Bath
   Home Assistant Error            Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 266, in runConcurrentThread
KeyError: u'last_updated'

   Home Assistant Error            plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by rlust** [comment]
I turned on debug and am now getting the following error:

  Home Assistant                  Starting device with address: person.randy
   Home Assistant Debug            Device content:
{u'message': u'Entity not found.'}
   Home Assistant Error            Error in plugin execution runConcurrentThread:

Traceback (most recent call last):
  File "plugin.py", line 266, in runConcurrentThread
KeyError: u'last_updated'

   Home Assistant Error            plugin runConcurrentThread function returned or failed (will attempt again in 10 seconds)

**Comment by rlust** [comment]
Found the issue. Had a device configured that should not be. A Person device.
